customhost = "employee.c3pxboqvh2pf.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "changyowlap-employee"
customregion = "us-east-1"
